name: Run aws-cdk
description: Run aws-cdk commands
author: tj-actions
inputs:
  cdk_stack:
    description: 'AWS CDK stack name to execute.'
    default: '*'
    required: false
  cdk_version:
    description: 'AWS CDK version to install.'
    default: 'latest'
    required: false
  cdk_subcommand:
    description: 'AWS CDK subcommand to execute.'
    required: true
  cdk_extra_args:
    description: 'AWS CDK subcommand arguments.'
    required: false
  working_dir:
    description: 'Working directory.'
    default: '.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Check stack status
      id: check
      working-directory: ${{ inputs.working_dir }}
      if: inputs.cdk_stack != '*'
      run: |
        stack_status=$(aws cloudformation describe-stacks --stack-name "${{ inputs.cdk_stack }}" --query 'Stacks[0].StackStatus' --output text)
        echo "Stack status: $stack_status"
        echo "stack_status=$stack_status" >> $GITHUB_OUTPUT
      shell: bash

    - name: Wait for stack update-complete
      working-directory: ${{ inputs.working_dir }}
      if: steps.check.outputs.stack_status == 'UPDATE_IN_PROGRESS'
      run: |
        echo "Waiting for "${{ inputs.cdk_stack }}" to complete updating..."
        aws cloudformation wait stack-update-complete --stack-name "${{ inputs.cdk_stack }}" 
        echo "${{ inputs.cdk_stack }} updated"
      shell: bash

    - name: Run aws-cdk
      id: aws-cdk
      working-directory: ${{ inputs.working_dir }}
      run: |
        npx -y cdk@${{ inputs.cdk_version }} ${{ inputs.cdk_subcommand }} ${{ inputs.cdk_extra_args }} "${{ inputs.cdk_stack }}"
      shell: bash
branding:
  icon: upload-cloud
  color: white
